/*
 * Project name:
     mmbInput.vtft
 * Generated by:
     Visual TFT
 * Date of creation
     7/16/2012
 * Time of creation
     8:51:10 AM
     
     
 * Created By:
 Andrew Hazelden
 
 * Email:
 andrewhazelden@gmail.com
 
 * Blog:
 http://www.andrewhazelden.com    
     
     
 * Test configuration:
     MCU:             P32MX460F512L
     Dev.Board:       MikroMMB_for_PIC32_hw_rev_1.10
                      http://www.mikroe.com/eng/products/view/595/mikrommb-for-pic32-board/
     Oscillator:      80000000 Hz
     SW:              mikroC PRO for PIC32
                      http://www.mikroe.com/eng/products/view/623/mikroc-pro-for-pic32/
                      
     Controller:      Mikromedia GAMING Shield
                      http://www.mikroe.com/eng/products/view/747/mikromedia-gaming-shield/
 */

#include "mmbInput_objects.h"

extern void InitGameShield();
extern void Check_GS();

extern long frame_counter; //Track the number of frames rendered

void main() {

  Start_TP();
  InitGameShield();    //Setup the gameshield inputs and outputs
  

  while (1) {
    Check_TP(); //Check the Mikromedia Touch Panel
    Check_GS(); //Check for Game Shield input
    
    frame_counter++;  //Increment the frame counter

  }

}
